services:
  scm-db:
    image: postgres:16-alpine
    container_name: scm-db
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - scm_db_data:/var/lib/postgresql/data

  scm-redis:
    image: redis:alpine
    container_name: scm-redis
    restart: always
    ports:
      - "6379:6379"

  scm-mq:
    image: rabbitmq:3-management
    container_name: scm-mq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  scm-api-gateway:
    build: ./apps/api-gateway
    image: scm-api-gateway:latest
    command: node dist/apps/api-gateway/src/server.js
    container_name: scm-api-gateway
    restart: always
    environment:
      - DEPLOY_MODE=monolith
      - PG_HOST=scm-db
      - REDIS_URL=redis://scm-redis:6379
      - RABBITMQ_URL=amqp://scm-mq
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
      - SNOWFLAKE_MACHINE_ID=1
    ports:
      - "3000:3000"
    depends_on:
      - scm-db
      - scm-redis
      - scm-mq
    env_file:
      - .env

  scm-order-service:
    build: ./apps/order-service
    image: scm-order-service:latest
    command: node dist/apps/order-service/src/server.js
    container_name: scm-order-service
    restart: always
    environment:
      - PG_HOST=scm-db
      - RABBITMQ_URL=amqp://scm-mq
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
      - SNOWFLAKE_MACHINE_ID=1
    depends_on:
      - scm-db
      - scm-mq
    env_file:
      - .env

  scm-inventory-worker:
    build: ./apps/inventory-worker
    image: scm-inventory-worker:latest
    command: node dist/apps/inventory-worker/src/worker.js
    container_name: scm-inventory-worker
    restart: always
    environment:
      - PG_HOST=scm-db
      - RABBITMQ_URL=amqp://scm-mq
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
    depends_on:
      - scm-db
      - scm-mq
    env_file:
      - .env

volumes:
  scm_db_data:
